version: "2"
services:
  front:
    build: .
    container_name: load-balancer
    ports:
      - "3030:3030"
    command: go run main.go 
  web1:
    image: strm/helloworld-http
  web2:
    image: strm/helloworld-http
  web3:
    image: strm/helloworld-http
  web4:
    image: strm/helloworld-http
  web5:
    image: strm/helloworld-http
