version: "2"
services:
  front:
    build: .
    container_name: load-balancer
    ports:
      - "3030:3030"
    command: ./run.sh # go run cmd/balancer/main.go 
  web1:
    image: strm/helloworld-http
    container_name: target-web1
  web2:
    image: strm/helloworld-http
    container_name: target-web2
  web3:
    image: strm/helloworld-http
    container_name: target-web3
  web4:
    image: strm/helloworld-http
    container_name: target-web4
  web5:
    image: strm/helloworld-http
    container_name: target-web5
